### ISSUE TITLE
Add support for ULO rates

### ISSUE THREAD

**Issue by axyjo** [jrfernandes/ontario_energy_board#34]
I don't think I see these in OEB's XML, but it'd be good to get a way to add ULO rates to Home Assistant.

**Comment by eprochasson** [comment]
Heya,

I wanted to give it a shot, but it looks like the Ontario Energy Board does not provide those rate in that XML document that is used to populate the values (or I failed to find them). The document is here: https://www.oeb.ca/open-data/current-electricity-rates-residential-rate-class

I contacted the OEB about this, let's see what happens,

**Comment by eprochasson** [comment]
Meanwhile, I made a quick template that seems to do the trick.

```yaml
template:
  - sensor:
      - name: "Electricity Rate"
        unique_id: local_electricity_rate
        state: >
          {% if 7 < now().hour < 23 and is_state('binary_sensor.workday_sensor', 'off') %}0.074
          {% elif now().hour > 23 or now().hour < 7 %}0.024
          {% elif 7 < now().hour < 16 or 21 < now().hour < 23 %}0.102
          {% else %}0.24{% endif %}
        device_class: energy
        unit_of_measurement: 'CAD/kWh'
```
